#!/bin/bash

log_error() {
  echo "$*" 1>&2
}

forsund --conf=./travis.conf --demon > /tmp/forsun.log 2>&1
FORSUND_PS=$(ps aux | grep forsund | grep -v grep)
if [ -z "$FORSUND_PS" ]
    then
        FORSUND_ERRORS=$(cat /tmp/forsun.log)
        log_error "forsund start failed for the following reasons:
                   $FORSUND_ERRORS
please run 'forsund' on your changes before committing."
    exit 1
fi

rm -rf /tmp/forsun_test
touch /tmp/forsun_test
forsun "set shell */2/1 * * * * * shell 'cmd=\"echo success > /tmp/forsun_test\"'"
sleep 3
CMD_SUCCEDS=$(echo "/tmp/forsun_test" | grep "success")
if [ -z "$CMD_SUCCEDS" ]
    then
        FORSUND_ERRORS=$(cat /tmp/forsun.log)
        log_error "forsun shell test failed for the following reasons:
                   $FORSUND_ERRORS
please run 'forsund' on your changes before committing."
        ps -ef | grep forsun | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
    exit 1
fi

ps -ef | grep forsun | grep -v grep | awk '{print $2}' | xargs kill -HUP > /dev/null 2>&1
exit 0