#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:tornado
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None

from tornado import gen
from tornado import stack_context

class Iface(object):
    def ping(self):
        pass

    def create(self, key, second, minute, hour, day, month, week, action, params):
        """
        Parameters:
         - key
         - second
         - minute
         - hour
         - day
         - month
         - week
         - action
         - params
        """
        pass

    def createTimeout(self, key, second, minute, hour, day, month, week, count, action, params):
        """
        Parameters:
         - key
         - second
         - minute
         - hour
         - day
         - month
         - week
         - count
         - action
         - params
        """
        pass

    def remove(self, key):
        """
        Parameters:
         - key
        """
        pass

    def get(self, key):
        """
        Parameters:
         - key
        """
        pass

    def getCurrent(self):
        pass

    def getTime(self, timestamp):
        """
        Parameters:
         - timestamp
        """
        pass

    def getKeys(self, prefix):
        """
        Parameters:
         - prefix
        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
      self._iprot = self._oprot = iprot
      if oprot is not None:
        self._oprot = oprot
      self._seqid = 0

    @gen.coroutine
    def ping(self):
        self._seqid += 1
        self.send_ping()
        result = yield self.recv_ping()
        raise gen.Return(result)

    def send_ping(self):
        self._oprot.writeMessageBegin('ping', TMessageType.CALL, self._seqid)
        args = ping_args()
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_ping(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = ping_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "ping failed: unknown result");

    @gen.coroutine
    def create(self, key, second, minute, hour, day, month, week, action, params):
        """
        Parameters:
         - key
         - second
         - minute
         - hour
         - day
         - month
         - week
         - action
         - params
        """
        self._seqid += 1
        self.send_create(key, second, minute, hour, day, month, week, action, params)
        result = yield self.recv_create()
        raise gen.Return(result)

    def send_create(self, key, second, minute, hour, day, month, week, action, params):
        self._oprot.writeMessageBegin('create', TMessageType.CALL, self._seqid)
        args = create_args()
        args.key = key
        args.second = second
        args.minute = minute
        args.hour = hour
        args.day = day
        args.month = month
        args.week = week
        args.action = action
        args.params = params
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_create(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = create_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        if result.err is not None:
          raise gen.Return(result.err)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "create failed: unknown result");

    @gen.coroutine
    def createTimeout(self, key, second, minute, hour, day, month, week, count, action, params):
        """
        Parameters:
         - key
         - second
         - minute
         - hour
         - day
         - month
         - week
         - count
         - action
         - params
        """
        self._seqid += 1
        self.send_createTimeout(key, second, minute, hour, day, month, week, count, action, params)
        result = yield self.recv_createTimeout()
        raise gen.Return(result)

    def send_createTimeout(self, key, second, minute, hour, day, month, week, count, action, params):
        self._oprot.writeMessageBegin('createTimeout', TMessageType.CALL, self._seqid)
        args = createTimeout_args()
        args.key = key
        args.second = second
        args.minute = minute
        args.hour = hour
        args.day = day
        args.month = month
        args.week = week
        args.count = count
        args.action = action
        args.params = params
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_createTimeout(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = createTimeout_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        if result.err is not None:
          raise gen.Return(result.err)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "createTimeout failed: unknown result");

    @gen.coroutine
    def remove(self, key):
        """
        Parameters:
         - key
        """
        self._seqid += 1
        self.send_remove(key)
        result = yield self.recv_remove()
        raise gen.Return(result)

    def send_remove(self, key):
        self._oprot.writeMessageBegin('remove', TMessageType.CALL, self._seqid)
        args = remove_args()
        args.key = key
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_remove(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = remove_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        if result.err is not None:
          raise gen.Return(result.err)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "remove failed: unknown result");

    @gen.coroutine
    def get(self, key):
        """
        Parameters:
         - key
        """
        self._seqid += 1
        self.send_get(key)
        result = yield self.recv_get()
        raise gen.Return(result)

    def send_get(self, key):
        self._oprot.writeMessageBegin('get', TMessageType.CALL, self._seqid)
        args = get_args()
        args.key = key
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_get(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = get_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        if result.err is not None:
          raise gen.Return(result.err)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "get failed: unknown result");

    @gen.coroutine
    def getCurrent(self):
        self._seqid += 1
        self.send_getCurrent()
        result = yield self.recv_getCurrent()
        raise gen.Return(result)

    def send_getCurrent(self):
        self._oprot.writeMessageBegin('getCurrent', TMessageType.CALL, self._seqid)
        args = getCurrent_args()
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_getCurrent(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = getCurrent_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "getCurrent failed: unknown result");

    @gen.coroutine
    def getTime(self, timestamp):
        """
        Parameters:
         - timestamp
        """
        self._seqid += 1
        self.send_getTime(timestamp)
        result = yield self.recv_getTime()
        raise gen.Return(result)

    def send_getTime(self, timestamp):
        self._oprot.writeMessageBegin('getTime', TMessageType.CALL, self._seqid)
        args = getTime_args()
        args.timestamp = timestamp
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_getTime(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = getTime_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "getTime failed: unknown result");

    @gen.coroutine
    def getKeys(self, prefix):
        """
        Parameters:
         - prefix
        """
        self._seqid += 1
        self.send_getKeys(prefix)
        result = yield self.recv_getKeys()
        raise gen.Return(result)

    def send_getKeys(self, prefix):
        self._oprot.writeMessageBegin('getKeys', TMessageType.CALL, self._seqid)
        args = getKeys_args()
        args.prefix = prefix
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    @gen.coroutine
    def recv_getKeys(self):
        (fname, mtype, rseqid) = yield gen.Task(self._iprot.readMessageBegin)
        if mtype == TMessageType.EXCEPTION:
          x = TApplicationException()
          yield gen.Task(x.read, self._iprot)
          yield gen.Task(self._iprot.readMessageEnd)
          raise x
        result = getKeys_result()
        yield gen.Task(result.read, self._iprot)
        yield gen.Task(self._iprot.readMessageEnd)
        if result.success is not None:
          raise gen.Return(result.success)
        raise TApplicationException(TApplicationException.MISSING_RESULT, "getKeys failed: unknown result");


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["ping"] = Processor.process_ping
        self._processMap["create"] = Processor.process_create
        self._processMap["createTimeout"] = Processor.process_createTimeout
        self._processMap["remove"] = Processor.process_remove
        self._processMap["get"] = Processor.process_get
        self._processMap["getCurrent"] = Processor.process_getCurrent
        self._processMap["getTime"] = Processor.process_getTime
        self._processMap["getKeys"] = Processor.process_getKeys

    @gen.coroutine
    def process(self, iprot, oprot):
        (name, type, seqid) = yield gen.Task(iprot.readMessageBegin)
        if name not in self._processMap:
            yield gen.Task(iprot.skip,TType.STRUCT)
            yield gen.Task(iprot.readMessageEnd)
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
        else:
            yield gen.Task(self._processMap[name], self, seqid, iprot, oprot)

    @gen.coroutine
    def process_ping(self, seqid, iprot, oprot):
        args = ping_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = ping_result()
        result.success = yield gen.Task(self._handler.ping, )
        oprot.writeMessageBegin("ping", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    @gen.coroutine
    def process_create(self, seqid, iprot, oprot):
        args = create_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = create_result()

        def handle_exception(xtype, value, traceback):
            if xtype == ForsunPlanError:
                result.err = value
            return True

        with stack_context.ExceptionStackContext(handle_exception):
            result.success = yield gen.Task(self._handler.create, args.key, args.second, args.minute, args.hour, args.day, args.month, args.week, args.action, args.params)

        oprot.writeMessageBegin("create", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    @gen.coroutine
    def process_createTimeout(self, seqid, iprot, oprot):
        args = createTimeout_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = createTimeout_result()

        def handle_exception(xtype, value, traceback):
            if xtype == ForsunPlanError:
                result.err = value
            return True

        with stack_context.ExceptionStackContext(handle_exception):
            result.success = yield gen.Task(self._handler.createTimeout, args.key, args.second, args.minute, args.hour, args.day, args.month, args.week, args.count, args.action, args.params)

        oprot.writeMessageBegin("createTimeout", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    @gen.coroutine
    def process_remove(self, seqid, iprot, oprot):
        args = remove_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = remove_result()

        def handle_exception(xtype, value, traceback):
            if xtype == ForsunPlanError:
                result.err = value
            return True

        with stack_context.ExceptionStackContext(handle_exception):
            result.success = yield gen.Task(self._handler.remove, args.key)

        oprot.writeMessageBegin("remove", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    @gen.coroutine
    def process_get(self, seqid, iprot, oprot):
        args = get_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = get_result()

        def handle_exception(xtype, value, traceback):
            if xtype == ForsunPlanError:
                result.err = value
            return True

        with stack_context.ExceptionStackContext(handle_exception):
            result.success = yield gen.Task(self._handler.get, args.key)

        oprot.writeMessageBegin("get", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    @gen.coroutine
    def process_getCurrent(self, seqid, iprot, oprot):
        args = getCurrent_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = getCurrent_result()
        result.success = yield gen.Task(self._handler.getCurrent, )
        oprot.writeMessageBegin("getCurrent", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    @gen.coroutine
    def process_getTime(self, seqid, iprot, oprot):
        args = getTime_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = getTime_result()
        result.success = yield gen.Task(self._handler.getTime, args.timestamp)
        oprot.writeMessageBegin("getTime", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    @gen.coroutine
    def process_getKeys(self, seqid, iprot, oprot):
        args = getKeys_args()
        yield gen.Task(args.read,iprot)
        yield gen.Task(iprot.readMessageEnd)
        result = getKeys_result()
        result.success = yield gen.Task(self._handler.getKeys, args.prefix)
        oprot.writeMessageBegin("getKeys", TMessageType.REPLY, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class ping_args:

    thrift_spec = (
    )

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('ping_args')
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class ping_result:
    """
    Attributes:
     - success
    """

    thrift_spec = (
        (0, TType.I16, 'success', None, None, ), # 0
    )

    def __init__(self, success=None,):
        self.success = success

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.I16:
                    self.success = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('ping_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.I16, 0)
            oprot.writeI16(self.success)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class create_args:
    """
    Attributes:
     - key
     - second
     - minute
     - hour
     - day
     - month
     - week
     - action
     - params
    """

    thrift_spec = (
        None, # 0
        (1, TType.STRING, 'key', None, None, ), # 1
        (2, TType.I16, 'second', None, None, ), # 2
        (3, TType.I16, 'minute', None, -1, ), # 3
        (4, TType.I16, 'hour', None, -1, ), # 4
        (5, TType.I16, 'day', None, -1, ), # 5
        (6, TType.I16, 'month', None, -1, ), # 6
        (7, TType.I16, 'week', None, -1, ), # 7
        (8, TType.STRING, 'action', None, "shell", ), # 8
        (9, TType.LIST, 'params', (TType.STRING,None), [
        ], ), # 9
    )

    def __init__(self, key=None, second=None, minute=thrift_spec[3][4], hour=thrift_spec[4][4], day=thrift_spec[5][4], month=thrift_spec[6][4], week=thrift_spec[7][4], action=thrift_spec[8][4], params=thrift_spec[9][4],):
        self.key = key
        self.second = second
        self.minute = minute
        self.hour = hour
        self.day = day
        self.month = month
        self.week = week
        self.action = action
        if params is self.thrift_spec[9][4]:
          params = [
        ]
        self.params = params

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.key = yield gen.Task(iprot.readString)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 2:
                if ftype == TType.I16:
                    self.second = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 3:
                if ftype == TType.I16:
                    self.minute = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 4:
                if ftype == TType.I16:
                    self.hour = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 5:
                if ftype == TType.I16:
                    self.day = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 6:
                if ftype == TType.I16:
                    self.month = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 7:
                if ftype == TType.I16:
                    self.week = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.action = yield gen.Task(iprot.readString)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 9:
                if ftype == TType.LIST:
                    self.params = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in xrange(_size0):
                        _elem5 = yield gen.Task(iprot.readString)
                        self.params.append(_elem5)
                    iprot.readListEnd()
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('create_args')
        if self.key is not None:
            oprot.writeFieldBegin('key', TType.STRING, 1)
            oprot.writeString(self.key)
            oprot.writeFieldEnd()
        if self.second is not None:
            oprot.writeFieldBegin('second', TType.I16, 2)
            oprot.writeI16(self.second)
            oprot.writeFieldEnd()
        if self.minute is not None:
            oprot.writeFieldBegin('minute', TType.I16, 3)
            oprot.writeI16(self.minute)
            oprot.writeFieldEnd()
        if self.hour is not None:
            oprot.writeFieldBegin('hour', TType.I16, 4)
            oprot.writeI16(self.hour)
            oprot.writeFieldEnd()
        if self.day is not None:
            oprot.writeFieldBegin('day', TType.I16, 5)
            oprot.writeI16(self.day)
            oprot.writeFieldEnd()
        if self.month is not None:
            oprot.writeFieldBegin('month', TType.I16, 6)
            oprot.writeI16(self.month)
            oprot.writeFieldEnd()
        if self.week is not None:
            oprot.writeFieldBegin('week', TType.I16, 7)
            oprot.writeI16(self.week)
            oprot.writeFieldEnd()
        if self.action is not None:
            oprot.writeFieldBegin('action', TType.STRING, 8)
            oprot.writeString(self.action)
            oprot.writeFieldEnd()
        if self.params is not None:
            oprot.writeFieldBegin('params', TType.LIST, 9)
            oprot.writeListBegin(TType.STRING, len(self.params))
            for iter6 in self.params:
                oprot.writeString(iter6)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class create_result:
    """
    Attributes:
     - success
     - err
    """

    thrift_spec = (
        (0, TType.STRUCT, 'success', (ForsunPlan, ForsunPlan.thrift_spec), None, ), # 0
        (1, TType.STRUCT, 'err', (ForsunPlanError, ForsunPlanError.thrift_spec), None, ), # 1
    )

    def __init__(self, success=None, err=None,):
        self.success = success
        self.err = err

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = ForsunPlan()
                    self.success.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.err = ForsunPlanError()
                    self.err.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('create_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.err is not None:
            oprot.writeFieldBegin('err', TType.STRUCT, 1)
            self.err.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class createTimeout_args:
    """
    Attributes:
     - key
     - second
     - minute
     - hour
     - day
     - month
     - week
     - count
     - action
     - params
    """

    thrift_spec = (
        None, # 0
        (1, TType.STRING, 'key', None, None, ), # 1
        (2, TType.I16, 'second', None, None, ), # 2
        (3, TType.I16, 'minute', None, -1, ), # 3
        (4, TType.I16, 'hour', None, -1, ), # 4
        (5, TType.I16, 'day', None, -1, ), # 5
        (6, TType.I16, 'month', None, -1, ), # 6
        (7, TType.I16, 'week', None, -1, ), # 7
        (8, TType.I16, 'count', None, 0, ), # 8
        (9, TType.STRING, 'action', None, "shell", ), # 9
        (10, TType.LIST, 'params', (TType.STRING,None), [
        ], ), # 10
    )

    def __init__(self, key=None, second=None, minute=thrift_spec[3][4], hour=thrift_spec[4][4], day=thrift_spec[5][4], month=thrift_spec[6][4], week=thrift_spec[7][4], count=thrift_spec[8][4], action=thrift_spec[9][4], params=thrift_spec[10][4],):
        self.key = key
        self.second = second
        self.minute = minute
        self.hour = hour
        self.day = day
        self.month = month
        self.week = week
        self.count = count
        self.action = action
        if params is self.thrift_spec[10][4]:
          params = [
        ]
        self.params = params

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.key = yield gen.Task(iprot.readString)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 2:
                if ftype == TType.I16:
                    self.second = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 3:
                if ftype == TType.I16:
                    self.minute = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 4:
                if ftype == TType.I16:
                    self.hour = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 5:
                if ftype == TType.I16:
                    self.day = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 6:
                if ftype == TType.I16:
                    self.month = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 7:
                if ftype == TType.I16:
                    self.week = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 8:
                if ftype == TType.I16:
                    self.count = yield gen.Task(iprot.readI16)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 9:
                if ftype == TType.STRING:
                    self.action = yield gen.Task(iprot.readString)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 10:
                if ftype == TType.LIST:
                    self.params = []
                    (_etype10, _size7) = iprot.readListBegin()
                    for _i11 in xrange(_size7):
                        _elem12 = yield gen.Task(iprot.readString)
                        self.params.append(_elem12)
                    iprot.readListEnd()
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('createTimeout_args')
        if self.key is not None:
            oprot.writeFieldBegin('key', TType.STRING, 1)
            oprot.writeString(self.key)
            oprot.writeFieldEnd()
        if self.second is not None:
            oprot.writeFieldBegin('second', TType.I16, 2)
            oprot.writeI16(self.second)
            oprot.writeFieldEnd()
        if self.minute is not None:
            oprot.writeFieldBegin('minute', TType.I16, 3)
            oprot.writeI16(self.minute)
            oprot.writeFieldEnd()
        if self.hour is not None:
            oprot.writeFieldBegin('hour', TType.I16, 4)
            oprot.writeI16(self.hour)
            oprot.writeFieldEnd()
        if self.day is not None:
            oprot.writeFieldBegin('day', TType.I16, 5)
            oprot.writeI16(self.day)
            oprot.writeFieldEnd()
        if self.month is not None:
            oprot.writeFieldBegin('month', TType.I16, 6)
            oprot.writeI16(self.month)
            oprot.writeFieldEnd()
        if self.week is not None:
            oprot.writeFieldBegin('week', TType.I16, 7)
            oprot.writeI16(self.week)
            oprot.writeFieldEnd()
        if self.count is not None:
            oprot.writeFieldBegin('count', TType.I16, 8)
            oprot.writeI16(self.count)
            oprot.writeFieldEnd()
        if self.action is not None:
            oprot.writeFieldBegin('action', TType.STRING, 9)
            oprot.writeString(self.action)
            oprot.writeFieldEnd()
        if self.params is not None:
            oprot.writeFieldBegin('params', TType.LIST, 10)
            oprot.writeListBegin(TType.STRING, len(self.params))
            for iter13 in self.params:
                oprot.writeString(iter13)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class createTimeout_result:
    """
    Attributes:
     - success
     - err
    """

    thrift_spec = (
        (0, TType.STRUCT, 'success', (ForsunPlan, ForsunPlan.thrift_spec), None, ), # 0
        (1, TType.STRUCT, 'err', (ForsunPlanError, ForsunPlanError.thrift_spec), None, ), # 1
    )

    def __init__(self, success=None, err=None,):
        self.success = success
        self.err = err

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = ForsunPlan()
                    self.success.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.err = ForsunPlanError()
                    self.err.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('createTimeout_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.err is not None:
            oprot.writeFieldBegin('err', TType.STRUCT, 1)
            self.err.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class remove_args:
    """
    Attributes:
     - key
    """

    thrift_spec = (
        None, # 0
        (1, TType.STRING, 'key', None, None, ), # 1
    )

    def __init__(self, key=None,):
        self.key = key

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.key = yield gen.Task(iprot.readString)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('remove_args')
        if self.key is not None:
            oprot.writeFieldBegin('key', TType.STRING, 1)
            oprot.writeString(self.key)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class remove_result:
    """
    Attributes:
     - success
     - err
    """

    thrift_spec = (
        (0, TType.STRUCT, 'success', (ForsunPlan, ForsunPlan.thrift_spec), None, ), # 0
        (1, TType.STRUCT, 'err', (ForsunPlanError, ForsunPlanError.thrift_spec), None, ), # 1
    )

    def __init__(self, success=None, err=None,):
        self.success = success
        self.err = err

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = ForsunPlan()
                    self.success.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.err = ForsunPlanError()
                    self.err.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('remove_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.err is not None:
            oprot.writeFieldBegin('err', TType.STRUCT, 1)
            self.err.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class get_args:
    """
    Attributes:
     - key
    """

    thrift_spec = (
        None, # 0
        (1, TType.STRING, 'key', None, None, ), # 1
    )

    def __init__(self, key=None,):
        self.key = key

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.key = yield gen.Task(iprot.readString)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('get_args')
        if self.key is not None:
            oprot.writeFieldBegin('key', TType.STRING, 1)
            oprot.writeString(self.key)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class get_result:
    """
    Attributes:
     - success
     - err
    """

    thrift_spec = (
        (0, TType.STRUCT, 'success', (ForsunPlan, ForsunPlan.thrift_spec), None, ), # 0
        (1, TType.STRUCT, 'err', (ForsunPlanError, ForsunPlanError.thrift_spec), None, ), # 1
    )

    def __init__(self, success=None, err=None,):
        self.success = success
        self.err = err

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.STRUCT:
                    self.success = ForsunPlan()
                    self.success.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.err = ForsunPlanError()
                    self.err.read(iprot)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('get_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.STRUCT, 0)
            self.success.write(oprot)
            oprot.writeFieldEnd()
        if self.err is not None:
            oprot.writeFieldBegin('err', TType.STRUCT, 1)
            self.err.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class getCurrent_args:

    thrift_spec = (
    )

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('getCurrent_args')
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class getCurrent_result:
    """
    Attributes:
     - success
    """

    thrift_spec = (
        (0, TType.LIST, 'success', (TType.STRUCT,(ForsunPlan, ForsunPlan.thrift_spec)), None, ), # 0
    )

    def __init__(self, success=None,):
        self.success = success

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.LIST:
                    self.success = []
                    (_etype17, _size14) = iprot.readListBegin()
                    for _i18 in xrange(_size14):
                        _elem19 = ForsunPlan()
                        _elem19.read(iprot)
                        self.success.append(_elem19)
                    iprot.readListEnd()
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('getCurrent_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.LIST, 0)
            oprot.writeListBegin(TType.STRUCT, len(self.success))
            for iter20 in self.success:
                iter20.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class getTime_args:
    """
    Attributes:
     - timestamp
    """

    thrift_spec = (
        None, # 0
        (1, TType.I32, 'timestamp', None, None, ), # 1
    )

    def __init__(self, timestamp=None,):
        self.timestamp = timestamp

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.timestamp = yield gen.Task(iprot.readI32)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('getTime_args')
        if self.timestamp is not None:
            oprot.writeFieldBegin('timestamp', TType.I32, 1)
            oprot.writeI32(self.timestamp)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class getTime_result:
    """
    Attributes:
     - success
    """

    thrift_spec = (
        (0, TType.LIST, 'success', (TType.STRUCT,(ForsunPlan, ForsunPlan.thrift_spec)), None, ), # 0
    )

    def __init__(self, success=None,):
        self.success = success

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.LIST:
                    self.success = []
                    (_etype24, _size21) = iprot.readListBegin()
                    for _i25 in xrange(_size21):
                        _elem26 = ForsunPlan()
                        _elem26.read(iprot)
                        self.success.append(_elem26)
                    iprot.readListEnd()
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('getTime_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.LIST, 0)
            oprot.writeListBegin(TType.STRUCT, len(self.success))
            for iter27 in self.success:
                iter27.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class getKeys_args:
    """
    Attributes:
     - prefix
    """

    thrift_spec = (
        None, # 0
        (1, TType.STRING, 'prefix', None, None, ), # 1
    )

    def __init__(self, prefix=None,):
        self.prefix = prefix

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.prefix = yield gen.Task(iprot.readString)
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('getKeys_args')
        if self.prefix is not None:
            oprot.writeFieldBegin('prefix', TType.STRING, 1)
            oprot.writeString(self.prefix)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)

class getKeys_result:
    """
    Attributes:
     - success
    """

    thrift_spec = (
        (0, TType.LIST, 'success', (TType.STRING,None), None, ), # 0
    )

    def __init__(self, success=None,):
        self.success = success

    @gen.coroutine
    def read(self, iprot):
        if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
            fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
            return
        yield gen.Task(iprot.readStructBegin)
        while True:
            (fname, ftype, fid) = yield gen.Task(iprot.readFieldBegin)
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.LIST:
                    self.success = []
                    (_etype31, _size28) = iprot.readListBegin()
                    for _i32 in xrange(_size28):
                        _elem33 = yield gen.Task(iprot.readString)
                        self.success.append(_elem33)
                    iprot.readListEnd()
                else:
                    yield gen.Task(iprot.skip,ftype)
            else:
                yield gen.Task(iprot.skip,ftype)
            yield gen.Task(iprot.readFieldEnd)
        yield gen.Task(iprot.readStructEnd)

    def write(self, oprot):
        if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
            oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('getKeys_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.LIST, 0)
            oprot.writeListBegin(TType.STRING, len(self.success))
            for iter34 in self.success:
                oprot.writeString(iter34)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return


    def __repr__(self):
      L = ['%s=%r' % (key, value)
        for key, value in self.__dict__.iteritems()]
      return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
